# Nominal Encoding

Import of libs

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

Importing of dataser

In [2]:
df = pd.read_csv("credit.csv")
df.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,job,dependents,telephone,foreign_worker,default
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,skilled employee,1,yes,yes,1
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,skilled employee,1,none,yes,2
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,unskilled resident,2,none,yes,1
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,skilled employee,2,none,yes,1
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,skilled employee,2,none,yes,2


In [3]:
df["purpose"].value_counts()

purpose
radio/tv               280
car (new)              234
furniture              181
car (used)             103
business                97
education               50
repairs                 22
domestic appliances     12
others                  12
retraining               9
Name: count, dtype: int64

From the above we came to know that repairs , domastic appliances, other ,retraining can ge grouped in other

In [4]:
df["purpose"].value_counts().count()
#10 different values 

np.int64(10)

In [5]:
df["credit_history"].value_counts()

credit_history
repaid                    530
critical                  293
delayed                    88
fully repaid this bank     49
fully repaid               40
Name: count, dtype: int64

Limited ok ... otherws category is not required

In [6]:
df["credit_history"].value_counts().count()

np.int64(5)

In [7]:
df["property"].value_counts()

property
other                       332
real estate                 282
building society savings    232
unknown/none                154
Name: count, dtype: int64

In [8]:
df["housing"].value_counts()

housing
own         713
rent        179
for free    108
Name: count, dtype: int64

## One Hot Enoding

OHE Using pandas

In [9]:
pd.get_dummies(df,columns=["credit_history","property","housing"])

,checking_balance,months_loan_duration,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,residence_history,...,credit_history_fully repaid,credit_history_fully repaid this bank,credit_history_repaid,property_building society savings,property_other,property_real estate,property_unknown/none,housing_for free,housing_own,housing_rent
0,< 0 DM,6,radio/tv,1169,unknown,> 7 yrs,4,single male,none,4,...,False,False,False,False,False,True,False,False,True,False
1,1 - 200 DM,48,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,2,...,False,False,True,False,False,True,False,False,True,False
2,unknown,12,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,3,...,False,False,False,False,False,True,False,False,True,False
3,< 0 DM,42,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,4,...,False,False,True,True,False,False,False,True,False,False
4,< 0 DM,24,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,4,...,False,False,False,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,unknown,12,furniture,1736,< 100 DM,4 - 7 yrs,3,female,none,4,...,False,False,True,False,False,True,False,False,True,False
996,< 0 DM,30,car (used),3857,< 100 DM,1 - 4 yrs,4,divorced male,none,4,...,False,False,True,True,False,False,False,False,True,False
997,unknown,12,radio/tv,804,< 100 DM,> 7 yrs,4,single male,none,4,...,False,False,True,False,True,False,False,False,True,False
998,< 0 DM,45,radio/tv,1845,< 100 DM,1 - 4 yrs,4,single male,none,4,...,False,False,True,False,False,False,True,True,False,False


So in new dataframe old data has been deleted and new data or endoded data has been added in the last of the table.....

In [10]:
pd.get_dummies(df,columns=["credit_history","property","housing"],drop_first =True)

,checking_balance,months_loan_duration,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,residence_history,...,default,credit_history_delayed,credit_history_fully repaid,credit_history_fully repaid this bank,credit_history_repaid,property_other,property_real estate,property_unknown/none,housing_own,housing_rent
0,< 0 DM,6,radio/tv,1169,unknown,> 7 yrs,4,single male,none,4,...,1,False,False,False,False,False,True,False,True,False
1,1 - 200 DM,48,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,2,...,2,False,False,False,True,False,True,False,True,False
2,unknown,12,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,3,...,1,False,False,False,False,False,True,False,True,False
3,< 0 DM,42,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,4,...,1,False,False,False,True,False,False,False,False,False
4,< 0 DM,24,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,4,...,2,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,unknown,12,furniture,1736,< 100 DM,4 - 7 yrs,3,female,none,4,...,1,False,False,False,True,False,True,False,True,False
996,< 0 DM,30,car (used),3857,< 100 DM,1 - 4 yrs,4,divorced male,none,4,...,1,False,False,False,True,False,False,False,True,False
997,unknown,12,radio/tv,804,< 100 DM,> 7 yrs,4,single male,none,4,...,1,False,False,False,True,True,False,False,True,False
998,< 0 DM,45,radio/tv,1845,< 100 DM,1 - 4 yrs,4,single male,none,4,...,2,False,False,False,True,False,False,True,False,False


In the abouve column the dummy variable has been removed and multicollinearity has been handeled (each column 1 has been removed ans total of 3 columns has been removed)

In [11]:
df.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,job,dependents,telephone,foreign_worker,default
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,skilled employee,1,yes,yes,1
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,skilled employee,1,none,yes,2
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,unskilled resident,2,none,yes,1
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,skilled employee,2,none,yes,1
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,skilled employee,2,none,yes,2


In [12]:
fd = df[["months_loan_duration", "credit_history","purpose","installment_rate","personal_status","property","age","amount"]]

from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split (fd.iloc[:,:9],fd.iloc[:,-1],test_size=0.3)

In [13]:
x_train,"----------",y_train

(     months_loan_duration          credit_history    purpose  \
 548                    12  fully repaid this bank   radio/tv   
 138                    15                critical   radio/tv   
 785                    18                  repaid   business   
 331                    18                critical  education   
 505                    10                  repaid  car (new)   
 ..                    ...                     ...        ...   
 387                    18                critical  furniture   
 359                    30                  repaid  furniture   
 416                    12                  repaid  car (new)   
 483                    15                 delayed  furniture   
 689                    12                  repaid  car (new)   
 
      installment_rate personal_status                  property  age  amount  
 548                 4          female               real estate   24     626  
 138                 4     single male               real 

In [14]:
from sklearn.preprocessing import OneHotEncoder

# inside the function the parameter is passed to remove the first column of the mosified data 
# changing the datatype from dr=efult double into int 32
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype =np.int32) # object

In [15]:
x_train_new = ohe.fit_transform(x_train[["credit_history","purpose","personal_status","property"]])

x_test_new = ohe.transform(x_test[["credit_history","purpose","personal_status","property"]])

In [16]:
x_test_new,"---------------",x_train_new

(array([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=int32),
 '---------------',
 array([[0, 0, 1, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32))

In [17]:
# Adding the processed data into the data set 

x_train_final = np.hstack((
    x_train[["months_loan_duration","installment_rate","age","amount"]].values,
    x_train_new
))

# colomn reduced as the passing of drop parameter in the ohe object 
print (x_train_final.shape)
x_train_final


(700, 23)


array([[12,  4, 24, ...,  0,  1,  0],
       [15,  4, 35, ...,  0,  1,  0],
       [18,  4, 35, ...,  0,  0,  0],
       ...,
       [12,  4, 33, ...,  0,  1,  0],
       [15,  3, 30, ...,  0,  0,  0],
       [12,  1, 31, ...,  0,  0,  0]])

In [18]:
# Adding the processed data into the data set of train

x_test_final = np.hstack((
    x_test[["months_loan_duration","installment_rate","age","amount"]].values,
    x_test_new
))

# colomn reduced as the passing of drop parameter in the ohe object 
print(x_test_final.shape)
x_test_final

(300, 23)


array([[ 6,  4, 24, ...,  0,  0,  0],
       [ 9,  4, 25, ...,  0,  1,  0],
       [18,  3, 28, ...,  1,  0,  0],
       ...,
       [36,  4, 36, ...,  0,  1,  0],
       [12,  4, 40, ...,  1,  0,  0],
       [15,  2, 24, ...,  1,  0,  0]])

In [20]:
# This code will not run because the there is no such categories as brand and no such column with with large amount of categories

counts = fd['brand'].value_counts()
# used on the columns with many categories to make limited no of the categoriws and small categories into the others
fd['brand'].nunique()

# the which categories with count less then 100 
threshold = 100

repl = counts[counts <= threshold].index
# all the small categories will come under uncommon column as when we apply the ohe
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))


KeyError: 'brand'